blank_issues_enabled: false
contact_links:
  - name: "PowerScale Ansible Documentation"
    url: https://github.com/dell/ansible-powerscale
    about: Official PowerScale Ansible modules documentation and examples
  - name: "PowerScale OneFS Documentation"
    url: https://www.dell.com/support/kbdoc/en-us/000152189/powerscale-onefs-info-hubs
    about: Official PowerScale OneFS documentation and API references
  - name: "Ansible Galaxy - PowerScale Collection"
    url: https://galaxy.ansible.com/ui/repo/published/dellemc/powerscale/
    about: Browse and install the PowerScale Ansible collection
  - name: "Ansible PowerScale Support"
    url: mailto:ansible.team@dell.com
    about: Contact Dell team for Ansible PowerScale support and inquiries
