---
- name: Alert management operations on PowerScale Array
  hosts: localhost
  connection: local

  tasks:
    - name: Create alert rule with basic options.
      dellemc.powerscale.alert_rule:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ validate_certs }}"
        port: "{{ port }}"
        state: present
        name: test_alert_rule
        categories: []
        channels: ["SupportAssist"]
        condition: "NEW"
        eventgroup_ids: ["100010001"]
        exclude_eventgroup_ids: []
        interval: 0
        limit: 0
        severities: []
        transient: 0

    - name: Create alert rule with all options.
      dellemc.powerscale.alert_rule:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ validate_certs }}"
        port: "{{ port }}"
        state: present
        name: test_rule_new
        condition: "NEW"
        categories:
          - all
        channels:
          - SupportAssist
        eventgroup_ids:
          - 100010001
          - 100010002
          - 100010003
        exclude_eventgroup_ids:
          - 100010005
        interval: 11
        transient: 10
        limit: 10
        severities:
          - emergency
          - critical

    - name: Update alert rule.
      dellemc.powerscale.alert_rule:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ validate_certs }}"
        port: "{{ port }}"
        state: present
        name: test_rule_new
        condition: "NEW"
        categories:
          - SYS_DISK_EVENTS
          - NODE_STATUS_EVENTS
        channels:
          - SupportAssist
        eventgroup_ids:
          - 100010001
          - 100010002
        exclude_eventgroup_ids:
          - 100010005
        interval: 11
        transient: 10
        limit: 10
        severities:
          - emergency
          - critical

    - name: Delete alert rule.
      dellemc.powerscale.alert_rule:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ validate_certs }}"
        port: "{{ port }}"
        state: absent
        name: test_rule_new
