---
- name: Alert management operations on PowerScale Array
  hosts: localhost
  connection: local

  tasks:
    - name: Create alert condition with basic options.
      dellemc.powerscale.alert_management:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ verify_ssl }}"
        port: "{{ port }}"
        status: present
        name: test_alert_rule
        categories: []
        channels: ["SupportAssist"]
        condition: "NEW"
        eventgroup_ids: ["100010001"]
        exclude_eventgroup_ids: []
        interval: 0
        limit: 0
        severities: []
        transient: 0

    - name: Create alert condition with all options.
      dellemc.powerscale.alert_management:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ verify_ssl }}"
        port: "{{ port }}"
        status: present
        name: test_rule_new
        condition: "NEW"
        categories:
          - all
        channels:
          - SupportAssist
        eventgroup_ids:
          - 100010001
          - 100010002
          - 100010003
        exclude_eventgroup_ids:
          - 100010005
        interval: 11
        transient: 10
        limit: 10
        severities:
          - emergency
          - critical

    - name: Update alert condition.
      dellemc.powerscale.alert_management:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ verify_ssl }}"
        port: "{{ port }}"
        status: present
        name: test_rule_new
        condition: "NEW"
        categories:
          - SYS_DISK_EVENTS
          - NODE_STATUS_EVENTS
        channels:
          - SupportAssist
        eventgroup_ids:
          - 100010001
          - 100010002
        exclude_eventgroup_ids:
          - 100010005
        interval: 11
        transient: 10
        limit: 10
        severities:
          - emergency
          - critical

    - name: Update alert condition.
      dellemc.powerscale.alert_management:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: "{{ verify_ssl }}"
        port: "{{ port }}"
        state: absent
        name: test_rule_new
