---
- name: Network Settings Operations on PowerScale
  hosts: localhost
  connection: local
  vars:
    onefs_host: '10.**.**169'
    verify_ssl: false
    api_user: 'user'
    api_password: 'password'
    state_present: 'present'
    state_absent: 'absent'

  tasks:
    - name: Get Network settings
      dellemc.powerscale.networksettings:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        state: "{{ state_present }}"

    - name: Enable source based routing
      dellemc.powerscale.networksettings:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        enable_source_routing: true
        state: "{{ state_present }}"

    - name: Enable source based routing - Idempotency
      dellemc.powerscale.networksettings:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        enable_source_routing: true
        state: "{{ state_present }}"

    - name: Disable source based routing
      dellemc.powerscale.networksettings:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        enable_source_routing: false
        state: "{{ state_present }}"

    - name: Disable source based routing - Idempotency
      dellemc.powerscale.networksettings:
        onefs_host: "{{ onefs_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        enable_source_routing: false
        state: "{{ state_present }}"
