---
- name: NFS Global Settings Module Operations on PowerScale Storage
  hosts: localhost
  connection: local
  vars:
    onefs_host: "10.**.**.**"
    port_no: "1234"
    api_user: "user"
    api_password: "password"
    verify_ssl: false

  tasks:
    - name: Get NFS global settings
      dellemc.powerscale.nfs_global_settings:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ port_no }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"

    - name: Update service of NFS global settings
      dellemc.powerscale.nfs_global_settings:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ port_no }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        service: true
        nfsv3:
          nfsv3_enabled: false
        nfsv4:
          nfsv40_enabled: true
          nfsv41_enabled: true
          nfsv42_enabled: false
        rpc_minthreads: 17
        rpc_maxthreads: 20
        rquota_enabled: true

    - name: Update service of NFS global settings - Idempotency
      dellemc.powerscale.nfs_global_settings:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ port_no }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        service: true
        nfsv3:
          nfsv3_enabled: false
        nfsv4:
          nfsv40_enabled: true
          nfsv41_enabled: true
          nfsv42_enabled: false
        rpc_minthreads: 17
        rpc_maxthreads: 20
        rquota_enabled: true
