---
- name: SMB operations on PowerScale Array
  hosts: localhost
  connection: local
  vars:
    onefs_host: '10.**.**.**'
    port_no: '8080'
    verify_ssl: false
    api_user: 'user'
    api_password: 'password'
    smb_name: 'test_sample_smb'
    new_name: "new_test_sample_smb"
    non_system_access_zone: 'NonSystemAz'
    system_access_zone: 'System'
    system_az_path: "/ifs/SystemAzShare"
    non_system_az_path: "AnsibleShare"
    system_az_user: "ansible_test_user1"
    system_az_group: "test_group_1"
    non_system_az_user: "NonSystemAzUser1"
    non_system_az_fs_user: 'root'
    non_system_az_ad_user: 'devconad\ad_user_4'
    non_system_az_ldap_user: 'ldap_test_user_1'
    non_system_az_group: "NonSystemAzGroup1"
    non_system_az_fs_group: "guest"
    non_system_az_ad_group: 'devconad\ad_group_odd_users'
    non_system_az_ldap_group: 'sample_ldap_group_2'
    wellknown1: "wellknown"
    state_present: "present"
    state_absent: "absent"
    description: "smb description updated"

  tasks:
    - name: Create SMB share for system access zone
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        path: "{{ system_az_path }}"
        description: "{{ description }}"
        permissions:
          - user_name: "{{ system_az_user }}"
            permission: "full"
            permission_type: "allow"
          - group_name: "{{ system_az_group }}"
            permission: "read"
            permission_type: "allow"
          - wellknown: "everyone"
            permission: "read"
            permission_type: "allow"
        run_as_root:
          - name: "sample_user"
            type: "user"
            provider_type: "file"
            state: "allow"
          - name: "sample_group"
            type: "group"
            provider_type: "ldap"
            state: "allow"
        allow_delete_readonly: true
        allow_execute_always: true
        inheritable_path_acl: true
        state: "{{ state_present }}"

    - name: Create SMB share for system access zone
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        path: "/ifs"
        description: "{{ description }}"
        create_path: false
        allow_variable_expansion: true
        auto_create_directory: true
        continuously_available: true
        file_filter_extension:
          extensions:
            - 'sample_extension_1'
          type: "allow"
          state: "present-in-share"
        file_filtering_enabled: true
        ca_timeout:
          value: 60
          unit: "minutes"
        strict_ca_lockout: true
        change_notify: "all"
        oplocks: true
        impersonate_guest: "never"
        impersonate_user: "sample_user"
        host_acls:
          - name: "sample_host_acl_1"
            access_type: "allow"
          - name: "sample_host_acl_2"
            access_type: "deny"
        state: "present"

    - name: Modify description for an existing SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ system_access_zone }}"
        description: "new description"
        state: "{{ state_present }}"

    - name: Modify group permission for an existing SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        path: "{{ system_az_path }}"
        description: "{{ description }}"
        permissions:
          - group_name: "{{ system_az_group }}"
            permission: "write"
            permission_type: "allow"
        state: "{{ state_present }}"

    - name: Modify multiple params for an existing  SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        path: "/ifs"
        allow_variable_expansion: false
        auto_create_directory: false
        file_filter_extension:
          extensions:
            - 'sample_extension_2'
          type: "allow"
          state: "absent-in-share"
        file_filtering_enabled: true
        ca_timeout:
          value: 15
          unit: "minutes"
        strict_ca_lockout: false
        change_notify: "norecurse"
        oplocks: false
        impersonate_guest: "always"
        impersonate_user: "new_user_2"
        host_acls:
          - name: "sample_host_acl_1"
            access_type: "deny"
          - name: "sample_host_acl_2"
            access_type: "allow"
        run_as_root:
          - name: "sample_user"
            type: "user"
            provider_type: "file"
            state: "deny"
          - name: "Batch"
            type: "wellknown"
            state: "allow"
        allow_delete_readonly: false
        allow_execute_always: false
        inheritable_path_acl: false
        state: "present"

    - name: Delete existing SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ system_access_zone }}"
        state: "{{ state_absent }}"

    - name: Create SMB share for non system access zone
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        path: "{{ non_system_az_path }}"
        access_zone: "{{ non_system_access_zone }}"
        description: "{{ description }}"
        permissions:
          - user_name: "{{ non_system_az_user }}"
            permission: "full"
            permission_type: "allow"
          - user_name: "{{ non_system_az_fs_user }}"
            permission: "read"
            permission_type: "allow"
            provider_type: "file"
          - group_name: "{{ non_system_az_group }}"
            permission: "read"
            permission_type: "allow"
          - group_name: "{{ non_system_az_fs_group }}"
            permission: "read"
            permission_type: "allow"
            provider_type: "file"
          - wellknown: "everyone"
            permission: "read"
            permission_type: "allow"
        state: "{{ state_present }}"

    - name: Modify description for an existing non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ non_system_access_zone }}"
        description: "new description"
        state: "{{ state_present }}"

    - name: Modify group permission for a non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ non_system_access_zone }}"
        path: "{{ non_system_az_path }}"
        description: "{{ description }}"
        permissions:
          - group_name: "{{ non_system_az_group }}"
            permission: "write"
            permission_type: "allow"
          - group_name: "{{ non_system_az_fs_group }}"
            permission: "write"
            permission_type: "allow"
            provider_type: "file"
        state: "{{ state_present }}"

    - name: Add AD user permission for a non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ non_system_access_zone }}"
        permissions:
          - user_name: '{{ non_system_az_ad_user }}'
            permission: "read"
            permission_type: "allow"
            provider_type: "ads"
          - group_name: '{{ non_system_az_ad_group }}'
            permission: "read"
            permission_type: "allow"
            provider_type: "ads"
        state: "{{ state_present }}"

    - name: Modify AD user permission for a non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        description: "{{ description }}"
        access_zone: "{{ non_system_access_zone }}"
        permissions:
          - user_name: "{{ non_system_az_ad_user }}"
            permission: "write"
            permission_type: "allow"
            provider_type: "ads"
          - group_name: "{{ non_system_az_ad_group }}"
            permission: "write"
            permission_type: "allow"
            provider_type: "ads"
        state: "{{ state_present }}"

    - name: Add ldap user permission for a non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ non_system_access_zone }}"
        permissions:
          - user_name: '{{ non_system_az_ldap_user }}'
            permission: "read"
            permission_type: "allow"
            provider_type: "ldap"
          - group_name: '{{ non_system_az_ldap_group }}'
            permission: "read"
            permission_type: "allow"
            provider_type: "ldap"
        state: "{{ state_present }}"

    - name: Modify ldap user permission for a non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        access_zone: "{{ non_system_access_zone }}"
        permissions:
          - user_name: '{{ non_system_az_ldap_user }}'
            permission: "write"
            permission_type: "allow"
            provider_type: "ldap"
          - group_name: '{{ non_system_az_ldap_group }}'
            permission: "read"
            permission_type: "deny"
            provider_type: "ldap"
        state: "{{ state_present }}"

    - name: Modify name for an existing non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ smb_name }}"
        new_share_name: "{{ new_name }}"
        access_zone: "{{ non_system_access_zone }}"
        state: "{{ state_present }}"

    - name: Get details of a non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ new_name }}"
        access_zone: "{{ non_system_access_zone }}"
        description: "new description"
        state: "{{ state_present }}"

    - name: Delete non system access zone SMB share
      dellemc.powerscale.smb:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        share_name: "{{ new_name }}"
        access_zone: "{{ non_system_access_zone }}"
        state: "{{ state_absent }}"
